name: Deploy App
on:
  workflow_run:
    workflows: ["Deloy Vault"]
    types: [requested]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VAULT_ADDR: "https://localhost:8200"

jobs:

  deploy-app:
    defaults:
      run:
        working-directory: "${{ github.workspace }}/tf"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - id: init
        run: |
          terraform init

      - id: validate
        run: |
          terraform validate -no-color

      - id: plan
        run: |
          terraform plan -no-color

      - id: apply
        run: |
          terraform apply -auto-approve -no-color ${{ steps.plan.outputs.stdout }}

      - run: |
          terraform show
          docker ps
