name: Deploy App
on:
  pull_request:
    type: [opened, reopened, synchronize]
  push:
    branches:
      - master
    tags:
      - v\d+\.\d+\.\d+

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: "${{ github.workspace }}/tf"

env:
  VAULT_ADDR: "https://localhost:8200"

jobs:

  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - id: init
        run: |
          terraform init

      - id: validate
        run: |
          terraform validate --no-color

      - id: plan
        run: |
          terraform plan --no-color
