name: Deploy App
on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency: 
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  VAULT_ADDR: "http://localhost:8200"

jobs:

  deploy-app:
    runs-on: ubuntu-22.04

    steps:
      - name: set env
        shell: bash
        run: |
         if [ ${GITHUB_REF##*/} = "main" ]; then
           echo "VAULT_TOKEN=${{ secrets.STAGING_VAULT_ROOT_TOKEN }}" >> $GITHUB_ENV
         elif [[ ${GITHUB_REF##*/} =~ ^v[0-9]+\.[0-9]+\.[0-9] ]]; then
           echo "VAULT_TOKEN=${{ secrets.PROD_VAULT_ROOT_TOKEN }}" >> $GITHUB_ENV
         else
           echo "VAULT_TOKEN=${{secrets.DEV_VAULT_ROOT_TOKEN}}" >> $GITHUB_ENV
         fi

      - uses: actions/checkout@v3

      - name: deploy vault instance
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "up -d"

      - uses: eLco/setup-vault@v1
        with:
          vault_version: 1.8.7

      - name: debug
        run: |
          docker ps
          docker images
          docker network ls
          docker logs workspace-vault-1

      - name: check vault secrets
        run: |
          vault secrets list

      - uses: hashicorp/setup-terraform@v2

      - id: init
        working-directory: tf
        run: |
          terraform init

      - id: plan
        working-directory: tf
        run: |
          terraform plan -no-color

      - id: apply
        working-directory: tf
        run: |
          echo "${{ steps.plan.outputs.stdout }}" | terraform apply -auto-approve -no-color -

      - run: |
        working-directory: tf
          terraform show
          docker ps
