---
name: CI Pipeline
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    tags:
      - v\d+\.\d+\.\d+

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  checkov:
    uses: "./.github/workflows/checkov.yml"

  lint:
    uses: "./.github/workflows/lint.yml"

  tfsec:
    uses: "./.github/workflows/tfsec.yml"
