name: tfsec
on:
  workflow_call:

jobs:

  tfsec:
    defaults:
      run:
        working-directory: "tf"
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: upload sarif file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
