name: Deploy Vault
on:
  pull_request:
    type: [opened, reopened, synchronize]
  workflow_call:

env:
  VAULT_ADDR: "http://localhost:8200"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy-vault:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: set env
        shell: bash
        run: |
         if [ ${GITHUB_REF##*/} = "master" ]; then
           echo "VAULT_TOKEN=${{ secrets.STAGING_VAULT_ROOT_TOKEN }}" >> $GITHUB_ENV
         elif [[ ${GITHUB_REF##*/} =~ ^v[0-9]+\.[0-9]+\.[0-9] ]]; then
           echo "VAULT_TOKEN=${{ secrets.PROD_VAULT_ROOT_TOKEN }}" >> $GITHUB_ENV
         else
           echo "VAULT_TOKEN=${{secrets.DEV_VAULT_ROOT_TOKEN}}" >> $GITHUB_ENV
         fi
      - name: deploy vault instance
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "up -d"

      - uses: eLco/setup-vault@v1
        with:
          vault_version: 1.8.7

      - name: debug
        run: |
          docker ps
          docker logs workspace-vault-1

      - name: check vault secrets
        run: |
          vault secrets list
